// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// g1
NumericMatrix g1(NumericVector T, int order);
RcppExport SEXP VNM_g1(SEXP TSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(g1(T, order));
    return __result;
END_RCPP
}
// g2
NumericMatrix g2(NumericVector T, double dt, int order);
RcppExport SEXP VNM_g2(SEXP TSEXP, SEXP dtSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(g2(T, dt, order));
    return __result;
END_RCPP
}
// f234
NumericMatrix f234(NumericVector T, double x, int order);
RcppExport SEXP VNM_f234(SEXP TSEXP, SEXP xSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(f234(T, x, order));
    return __result;
END_RCPP
}
// SDM
double SDM(NumericMatrix M);
RcppExport SEXP VNM_SDM(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(SDM(M));
    return __result;
END_RCPP
}
// Trans
NumericMatrix Trans(NumericMatrix M);
RcppExport SEXP VNM_Trans(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(Trans(M));
    return __result;
END_RCPP
}
// Minus
NumericMatrix Minus(NumericMatrix M1, NumericMatrix M2);
RcppExport SEXP VNM_Minus(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M2(M2SEXP);
    __result = Rcpp::wrap(Minus(M1, M2));
    return __result;
END_RCPP
}
// Plus
NumericMatrix Plus(NumericMatrix M1, NumericMatrix M2);
RcppExport SEXP VNM_Plus(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M2(M2SEXP);
    __result = Rcpp::wrap(Plus(M1, M2));
    return __result;
END_RCPP
}
// Multiple
NumericMatrix Multiple(NumericMatrix M1, NumericMatrix M2);
RcppExport SEXP VNM_Multiple(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M2(M2SEXP);
    __result = Rcpp::wrap(Multiple(M1, M2));
    return __result;
END_RCPP
}
// infor234
NumericMatrix infor234(NumericVector T, double x, int order);
RcppExport SEXP VNM_infor234(SEXP TSEXP, SEXP xSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(infor234(T, x, order));
    return __result;
END_RCPP
}
// d1
double d1(NumericVector T, double x, double xl, NumericMatrix inv, int order);
RcppExport SEXP VNM_d1(SEXP TSEXP, SEXP xSEXP, SEXP xlSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(d1(T, x, xl, inv, order));
    return __result;
END_RCPP
}
// d2
double d2(NumericVector T, double x, double xl, NumericMatrix inv, int order);
RcppExport SEXP VNM_d2(SEXP TSEXP, SEXP xSEXP, SEXP xlSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(d2(T, x, xl, inv, order));
    return __result;
END_RCPP
}
// d3
double d3(NumericVector T, double x, double xl, NumericMatrix inv, double dt, int order);
RcppExport SEXP VNM_d3(SEXP TSEXP, SEXP xSEXP, SEXP xlSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(d3(T, x, xl, inv, dt, order));
    return __result;
END_RCPP
}
// dd1
double dd1(NumericVector T, double x1, double x2, double xl, NumericMatrix inv, int order);
RcppExport SEXP VNM_dd1(SEXP TSEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP xlSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(dd1(T, x1, x2, xl, inv, order));
    return __result;
END_RCPP
}
// dd2
double dd2(NumericVector T, double x1, double x2, double xl, NumericMatrix inv, int order);
RcppExport SEXP VNM_dd2(SEXP TSEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP xlSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(dd2(T, x1, x2, xl, inv, order));
    return __result;
END_RCPP
}
// dd3
double dd3(NumericVector T, double x1, double x2, double xl, NumericMatrix inv, double dt, int order);
RcppExport SEXP VNM_dd3(SEXP TSEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP xlSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(dd3(T, x1, x2, xl, inv, dt, order));
    return __result;
END_RCPP
}
// ds1
double ds1(NumericVector T, double x, NumericMatrix inv, int order);
RcppExport SEXP VNM_ds1(SEXP TSEXP, SEXP xSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(ds1(T, x, inv, order));
    return __result;
END_RCPP
}
// ds2
double ds2(NumericVector T, double x, NumericMatrix inv, int order);
RcppExport SEXP VNM_ds2(SEXP TSEXP, SEXP xSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(ds2(T, x, inv, order));
    return __result;
END_RCPP
}
// ds3
double ds3(NumericVector T, double x, NumericMatrix inv, double dt, int order);
RcppExport SEXP VNM_ds3(SEXP TSEXP, SEXP xSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(ds3(T, x, inv, dt, order));
    return __result;
END_RCPP
}
// sMultiple
NumericMatrix sMultiple(double s, NumericMatrix M);
RcppExport SEXP VNM_sMultiple(SEXP sSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    __result = Rcpp::wrap(sMultiple(s, M));
    return __result;
END_RCPP
}
// upinfor
NumericMatrix upinfor(NumericVector W, NumericVector T, NumericVector X, int order);
RcppExport SEXP VNM_upinfor(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(upinfor(W, T, X, order));
    return __result;
END_RCPP
}
// c1_weight_1
NumericVector c1_weight_1(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, int order);
RcppExport SEXP VNM_c1_weight_1(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(c1_weight_1(W, T, X, inv, order));
    return __result;
END_RCPP
}
// c1_weight_2
NumericMatrix c1_weight_2(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, int order);
RcppExport SEXP VNM_c1_weight_2(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(c1_weight_2(W, T, X, inv, order));
    return __result;
END_RCPP
}
// c_weight_1
NumericVector c_weight_1(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, double dt, int order);
RcppExport SEXP VNM_c_weight_1(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(c_weight_1(W, T, X, inv, dt, order));
    return __result;
END_RCPP
}
// c_weight_2
NumericMatrix c_weight_2(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, double dt, int order);
RcppExport SEXP VNM_c_weight_2(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(c_weight_2(W, T, X, inv, dt, order));
    return __result;
END_RCPP
}
// D_weight_1
NumericVector D_weight_1(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, int order);
RcppExport SEXP VNM_D_weight_1(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(D_weight_1(W, T, X, inv, order));
    return __result;
END_RCPP
}
// D_weight_2
NumericMatrix D_weight_2(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, int order);
RcppExport SEXP VNM_D_weight_2(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    __result = Rcpp::wrap(D_weight_2(W, T, X, inv, order));
    return __result;
END_RCPP
}
// M_weight_1
NumericVector M_weight_1(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, double dt, int order, NumericVector lambda);
RcppExport SEXP VNM_M_weight_1(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(M_weight_1(W, T, X, inv, dt, order, lambda));
    return __result;
END_RCPP
}
// M_weight_2
NumericMatrix M_weight_2(NumericVector W, NumericVector T, NumericVector X, NumericMatrix inv, double dt, int order, NumericVector lambda);
RcppExport SEXP VNM_M_weight_2(SEXP WSEXP, SEXP TSEXP, SEXP XSEXP, SEXP invSEXP, SEXP dtSEXP, SEXP orderSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inv(invSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(M_weight_2(W, T, X, inv, dt, order, lambda));
    return __result;
END_RCPP
}
